apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-demoapp
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    github.com/project-slug: rajatrj16/backstage-demoapp
  tags:
    - microservice
    - generated
spec:
  type: website
  owner: user:guest
  lifecycle: development
  system: services
